- config/settings/base.py
- sprints/dashboard/models.py
This fixes defining custom assignee/reviewer time with bot directives.
1. Set `.env` according to the ticket description.
1. Create superuser with `docker-compose -f local.yml run --rm django python manage.py createsuperuser` (the button on frontend should be visible for `staff` users only).
1. Add email to your superuser account under `http://localhost:8000/admin/account/emailaddress/`.
1. Navigate to `frontend` and run `npm i && npm start`.
1. Log into the frontend.
1. Compare the results on `master` and this branch. Please use the linked forum post as a reference for checking the values.
> [BB-1247] Fix bot directives

- config/settings/base.py
- frontend/src/components/CompleteSprintsButton.js
- sprints/dashboard/libs/google.py
- sprints/dashboard/models.py
- sprints/dashboard/tasks.py
- sprints/dashboard/tests/test_utils.py
- sprints/dashboard/utils.py
This adds removing archived tickets from the active sprint. Leaving them might interrupt closing the sprint properly.
Minor fixes included here:
- adds confirmation after clicking the `Complete Sprints` button,
- disables running the code related to ending the sprint via the dev environment,
- ignores calendar events with specific hours (it was failing, because they don't have `start` and `end`),
- reduces the number of sprints uploaded to the spillover report to the last one (the sprint, in which the issue spilled over),
- improves sprint detection by introducing the fallback to another cell if the future sprint was not found in the current one - this happens if there are no issues scheduled for the sprint in the specific cell.
> [BB-1497] Move archived issues out of the sprint before closing it

- config/settings/base.py
- sprints/dashboard/utils.py
This is a hotfix for changed sprints naming convention. There is a typo in retrieving env variables, so we cannot just change it this way.
It doesn't handle cross-cell tickets, it just fixes the dashboard. The cross-cell tickets will be handled properly in #14.
> [BB-1603] Hotfix for sprints naming

- config/settings/base.py
- frontend/package-lock.json
- frontend/package.json
- sprints/dashboard/models.py
- sprints/dashboard/serializers.py
- sprints/dashboard/tasks.py
- sprints/dashboard/tests/test_utils.py
- sprints/dashboard/utils.py
This handles cross-cell tickets on the dashboard and adds a functionality to create new sprints while ending the current ones. It currently uses a workaround for dealing with currently shared sprints. There will be a follow-up to remove temporary workarounds after ending the current sprint (please see the `TODO` comments).
1. Set `.env` according to the ticket description.
1. Create superuser with `docker-compose -f local.yml run --rm django python manage.py createsuperuser` (the button on frontend should be visible for `staff` users only).
1. Add email to your superuser account under `http://localhost:8000/admin/account/emailaddress/`.
1. Navigate to `frontend` and run `npm i && npm start`.
1. Log into the frontend.
1. …
> [BB-1603] Split Jira sprints between cells and create new sprints via dashboard

- sprints/dashboard/libs/google.py
- sprints/dashboard/tasks.py
- sprints/dashboard/utils.py
This adds exporting the users' commitments at the end of the sprint into the Google Spreadsheet.
1. Set `.env` file.
1. Create superuser with `docker-compose -f local.yml run --rm django python manage.py createsuperuser` (the button on frontend will be visible for `staff` users only).
1. Add email to your superuser account under `http://localhost:8000/admin/account/emailaddress/`.
1. Navigate to `frontend` and run `npm i && npm start`.
1. Log into the frontend.
1. Click the red `Complete Sprints` button and confirm it.
1. Wait for the task to finish (it takes around a minute, because we need to run group of tasks synchronously, as using Celery 4 with Redis [seems to be …
> [BB-1548] Export sprint commitments at the end of the sprint

- config/settings/base.py
- sprints/dashboard/libs/google.py
- sprints/dashboard/libs/jira.py
- sprints/dashboard/models.py
- sprints/dashboard/tasks.py
- sprints/dashboard/tests/test_utils.py
- sprints/dashboard/utils.py
This adds the ability to retrieve spillover reasons from the comments. The comment with the spillover reason should match the following regexp:
```python
fr"\[~{JIRA_BOT_USERNAME}\]: <spillover>(.*)<\/spillover>"
```
1. Set `.env` file.
1. Checkout **`agrendalath/bb-1550-testing-branch`** (it includes dev condition for this ticket, which will allow testing this).
1. Create superuser with `docker-compose -f local.yml run --rm django python manage.py createsuperuser` (the button on frontend will be visible for `staff` users only).
1. Add email to your superuser account under `http://localhost:8000/admin/account/emailaddress/`.
1. Navigate to `frontend` and run `npm i && npm start`.
1. Log into the frontend.
1. Click the red …
> [BB-1550] Retrieve the spillover reason from the comment

- .circleci/config.yml
- config/settings/base.py
- frontend/.env
- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.js
- frontend/src/actions/auth.js
- frontend/src/actions/index.js
- frontend/src/actions/sprints.js
- frontend/src/components/Board.js
- frontend/src/components/Cells.js
- frontend/src/components/CompleteSprintsButton.js
- frontend/src/components/Login.js
- frontend/src/components/Table.css
- frontend/src/components/Table.js
- frontend/src/components/UserBoard.js
- frontend/src/components/UserTable.js
- frontend/src/constants/index.js
- frontend/src/reducers/index.js
- frontend/src/reducers/sprints.js
- frontend/src/routes.js
- local.yml
- requirements/local.txt
- sprints/dashboard/models.py
- sprints/dashboard/serializers.py
- sprints/dashboard/utils.py
This introduces the whole new view for the user - the single-user view, which shows the assignments for the particular user. To make the user-experience smooth here, some bigger reworks were required, i.e.:
- moving the cell/board data to Redux and caching it in Local Storage - thanks to this we can now browse smoothly between the dashboards and users, while the data is being fetched in the background and the dashboard is being updated dynamically,
- adding issues to the dashboard's serializer, because we originally had them on the backend side and we don't need to fetch them for each user (we're now just doing it to maintain the up-to-date status of the board).
1. Set `.env` file.
1. Set `JIRA_URL` and `REACT_APP_GOOGLE_CLIENT_ID` in `frontend/.env.local` file.
1. Start the backend with …
> [BB-1547] Add single-user view

- .circleci/config.yml
- config/settings/base.py
- frontend/package-lock.json
- frontend/package.json
- frontend/src/actions/sustainability.js
- frontend/src/components/sustainability/BudgetBoard.js
- frontend/src/components/sustainability/BudgetTable.js
- frontend/src/components/sustainability/SustainabilityBoard.js
- frontend/src/constants/index.js
- frontend/src/selectors/index.js
- frontend/src/selectors/sustainability.js
- frontend/src/selectors/sustainability.test.js
- sprints/dashboard/libs/jira.py
- sprints/dashboard/models.py
- sprints/dashboard/utils.py
- sprints/sustainability/migrations/0001_initial.py
- sprints/sustainability/models.py
- sprints/sustainability/serializers.py
- sprints/sustainability/utils.py
- sprints/sustainability/views.py
This greatly improves the accounts' retrieval performance and the reliability of the API by moving to the different Tempo API endpoint and making cell-related calculations being performed directly on frontend.
For gathering data from a year the difference for me was 1.5m -> 17s.
1. Set `.env` file (you can take find in a comment on the ticket).
1. Create frontend/.env.local and set REACT_APP_GOOGLE_CLIENT_ID there.
1. Load the fixtures (attached to the ticket) with `docker-compose -f local.yml exec django python manage.py loaddata fixtures_sprints.json`.
1. Navigate to frontend and run `npm i && npm start`.
1. Log in.
1. Check the Sustainability and Budget dashboard for overall/cells/yourself and see if the accounts look …
> [BB-1625] Rework retrieving accounts

- compose/local/django/Dockerfile
- config/settings/base.py
- config/urls.py
- frontend/src/actions/auth.js
- frontend/src/actions/sprints.js
- frontend/src/actions/sustainability.js
- frontend/src/components/sprint/SprintActionButtons.js
- frontend/src/constants/index.js
- frontend/src/middleware/api.js
- frontend/src/reducers/auth.js
- requirements/base.txt
- sprints/users/jwt.py
This implements JWT token refreshing. Access tokens will be valid for shorter (`JWT_ACCESS_TOKEN_LIFETIME_HOURS`) time and refresh tokens will be used to regenerate them. The refresh tokens are rotating, so we won't need to log in anymore as long as we visit the page once per `JWT_REFRESH_TOKEN_LIFETIME_DAYS` days.
I added one new line to envs on the ticket: `JWT_ACCESS_TOKEN_LIFETIME_HOURS=0.0004`. This will make access tokens last for less than 2 seconds, which will be enough for making singular requests and will speed up the testing.
1. Set `.env` file (you can find it in a comment on the ticket).
1. Start the backend with `docker-compose -f local.yml up --build` (`build` is important here; it will take a while, because our first layer of the Dockerfile has changed).
1. Run migrations …
> [BB-1718] Implement JWT token refreshing

- compose/production/django/Dockerfile
I forgot to add `git` dependency to prod's Dockerfile. I tested this with `docker-compose -f production.yml build` now.
Merging this as a trivial change.
> [BB-1718] Add missing dependency to prod Dockerfile

- sprints/sustainability/models.py
This is a hotfix for the single-vCPU deployment.
This is a trivial change, as we're using mostly IO (and not CPU) for `_fetch_accounts_chunk`.
> [BB-1625] Replace processes with threads

- config/settings/base.py
- sprints/dashboard/models.py
- sprints/dashboard/tasks.py
- sprints/dashboard/utils.py
This implements adding `Clean sprint` row to spillover spreadsheet. `Comment` field is collected from the specific cell's `Meetings` ticket. This way we can gather hints for achieving clean sprints.
1. Set `.env` file (you can find it in a comment on the ticket).
1. Add `members_with_clean_sprint = ["YOUR FULL NAME"]` under `sprints/dashboard/utils.py:427`.
1. Remove `and not settings.DEBUG` part in `sprints/dashboard/utils.py:442` line.
1. Create frontend/.env.local and set REACT_APP_GOOGLE_CLIENT_ID there.
1. Navigate to frontend and run `npm i && npm start`.
1. Go to the cell's board.
1. Use `Complete Sprint` button. Confirm.
1. Check the [dev spreadsheet](https://docs.google.com/spreadsheets/d/1Xlpt0WGanH6v4BgmqgZJ8bgH …
> [BB-1676] Add "clean sprint" rows to the spillover spreadsheet

- frontend/src/components/sprint/SprintActionButtons.js
- sprints/dashboard/tasks.py
- sprints/dashboard/utils.py
These small changes handle the following cases:
- add confirmation window for sprint actions that use Celery,
- use user names instead of their keys for creating tickets in Jira (apparently these two may differ in some cases),
- handle unassigned issues that spill over during the sprint (this should actually never happen, but it's better to be defensive here.
Merging it as a trivial change.
> [BB-1719] Follow-up fixes

- sprints/dashboard/models.py
Jira API returns `null` for tickets with accounts inherited from the parent tasks. We will just ignore these values now to prevent this from breaking.
> [BB-1320] Ignore inherited accounts in subtasks

- .circleci/config.yml
- compose/local/django/Dockerfile
- compose/production/django/Dockerfile
- config/settings/base.py
- config/settings/local.py
- config/settings/production.py
- config/settings/test.py
- frontend/src/actions/sprints.js
- frontend/src/components/sprint/Cells.js
- frontend/src/components/sprint/SprintActionButtons.js
- frontend/src/components/sustainability/BudgetBoard.js
- frontend/src/constants/index.js
- frontend/src/reducers/sprints.js
- local.yml
- requirements/local.txt
- setup.cfg
- sprints/dashboard/models.py
- sprints/dashboard/tasks.py
- sprints/dashboard/urls.py
- sprints/dashboard/utils.py
- sprints/dashboard/views.py
- sprints/sustainability/models.py
- sprints/sustainability/tasks.py
- sprints/sustainability/views.py
This implements caching the worklogs. Its purpose is to be as transparent as possible, so it doesn't alter the underlying logic.
This also includes locking the "Complete Sprint button" (described in the instructions), which needed caching changes to work properly.
I also updated Python to have more concise syntax with [assignment expressions (PEP 572)](https://www.python.org/dev/peps/pep-0572/).
1. Set `.env` file (you can find it in a comment on the ticket).
1. Set frontend/.env.local file (you can find it in a comment on the ticket).
1. Navigate to frontend and run `npm i && npm start`.
1. Log in.
1. Open http://localhost:5555/tasks (you can find the credentials in `.env` file) and wait for the tasks to complete. This …
> [BB-1816] Cache worklogs and lock "Complete Sprint" button

- config/settings/base.py
- sprints/dashboard/libs/google.py
- sprints/dashboard/models.py
This adds support for scheduling [special vacation](https://handbook.opencraft.com/en/latest/vacation/#special-vacation) - reduced time off.
Due to many mistakes and oversights we relaxed regex to treat any event starting with member's name as the vacation. Additionally, if it's followed with any word and then a number after which comers letter "h", it is treated as reduced time off - **the provided number of hours indicates user's availability per day**. Some working examples:
- Piotr off
- Piotr away
- Piotr reduced 4 h only
- Piotr reduced time off (4h/day)
1. Set `.env` file (you can find it in a comment on the ticket).
1. Create superuser with `docker-compose -f local.yml exec django python manage.py createsuperuser` …
> [BB-2186] Support special vacation

- sprints/dashboard/tasks.py
`future_next_sprint` is used by the `create_role_issues_task` below, but if the future sprint does not exist, then its value is `None`. Therefore we need to reassign this variable after creating new sprint.
> [BB-2276] Fix creating role-specific tickets when the future sprint does not exist

- sprints/dashboard/tests/test_utils.py
- sprints/dashboard/utils.py
This chages the way we are calculating Excel-like column names for Google Spreadsheets, as the previous implementation was buggy for letters after `Z`. It also adds some tests to ensure this won't happen again.
1. Open [this spreadsheet](https://docs.google.com/spreadsheets/d/1Xlpt0WGanH6v4BgmqgZJ8bgHVEBlmvyb7F-9sRxtInk/edit#gid=1636833065) on the `Bebop Commitments` tab and scroll to the last column on the right.
1. Set `.env` (you can find it in a comment on the ticket).
1. Build the backend with `docker-compose -f local.yml build`.
1. Run migrations with `docker-compose -f local.yml run django python manage.py migrate`.
1. Open Django shell with `docker-compose -f local.yml run django python manage.py shell_plus`.
1. Run the following commands there:
```python
from …
```
> [BB-2908] Fix calculating spreadsheet column names

- sprints/dashboard/models.py
This aligns the board with the logic behind retrieving commitments.
Merging as a hotfix.
> [Hotfix] Hide users not included in quickfilters

- README.rst
- config/settings/base.py
- frontend/src/components/Table.css
- frontend/src/components/sprint/Table.js
- frontend/src/components/sprint/UserTable.js
- sprints/dashboard/models.py
- sprints/dashboard/serializers.py
This contains the following changes:
1. Adds a toggle for ongoing work (spillovers). This is useful to for planning the next sprint upfront by making an assumption that all work from the current sprint will be completed on time.
1. Adds a toggle for flagged tickets. If tickets are preassigned and flagged, then the assignees can use this option to determine whether they need to pass on some tickets.
1. Nit: fixes `key` attributes of unestimated tickets in `Table.js`.
**Note:** while testing, you can see that the results might sometimes be off by 1 due to rounding.
1. Set `.env` and `frontend/env.local` (you can find them in a comment on the ticket).
1. Comment out [these two lines](https://github.com/open-craft/sprints/blob/agrendalath/bb-3130-hide_flagged_tickets/frontend/src/App.js#L87-L8 …
> [BB-3130] Allow hiding spillovers and flagged tickets

- sprints/dashboard/models.py
- sprints/dashboard/tests/test_models.py
This fixes a bug with calculating vacations for negative timezones from #59. That PR did not invert the division for negative timezones, so these cases were not being classified correctly:
1. Negative timezone, non-overlapping day, vacations at the last day of the active sprint. These were counted as a part of the next sprint instead of the active one.
2. Negative timezone, non-overlapping day, vacations at the last day of the next sprint. These were counted as a part of the future next sprint instead of the next one.
1. Check that the tests are passing.
> [BB-3173] Fix vacations for negative timezones

- config/settings/base.py
- config/urls.py
- requirements/base.txt
- sprints/dashboard/libs/google.py
- sprints/dashboard/libs/tests/test_google.py
- sprints/users/urls.py
- sprints/users/views.py
This:
1. Fixes Google auth, which broke due to two reasons:
1.1. The ones described in open-craft/django-rest-auth/pull/1.
1.2. Removal of required views as a part of the cleanup in #59.
1. Adds support for full names in vacation calendar events.
1. Set `.env` and `frontend/env.local` (you can find them in a comment in the Vault).
1. Comment out [these two lines](https://github.com/open-craft/sprints/blob/master/frontend/src/App.js#L87-L88). They're irrelevant to the scope and will only slow down the local environment.
1. Start the backend with `docker-compose -f local.yml up --build` (this is important because we're changing dependencies here).
1. Run migrations with `docker-compose -f local.yml exec django python manage.py migrate`.
1. Navigate to `frontend` directory and run `npm i && …
> [BB-3566] Fix name collisions and Google auth

- sprints/dashboard/utils.py
Jira orders sprints by their IDs, so if they were not created in chronological order, then we need to search for an active one.
Related error: https://sentry.io/organizations/opencraft/issues/2178293183/.
> Fix a case when sprints were not created in a chronological order

- sprints/dashboard/utils.py
Jira orders sprints by their IDs, so if they were not created in chronological order, then we need to search for an active one.
> Fix second case when sprints were not created in a chronological order

- config/settings/base.py
- sprints/dashboard/libs/jira.py
After deploying #69, which added the custom `Referer` header, it turned out that the `content-type` is no longer set correctly, resulting in HTTP 415 response from some endpoints. This adds the missing header, which is enough for our use cases - we are not using Jira endpoints with content types different than `application/json`.
> [BB-3174] Fix headers in API calls

- config/settings/base.py
- sprints/dashboard/automation.py
- sprints/dashboard/tests/test_automation.py
This fixes the edge case for detecting sprint injections. If the ticket is created with the "Sprint" value, this is not reflected in its changelog. This adds checking the ticket creation date.
1. Set `.env` (you can find them [here](https://vault.opencraft.com:8200/ui/vault/secrets/secret/show/core/Sprints%20Development%20Envs)). There were some recent changes.
1. Build the backend with `docker-compose -f local.yml build --pull`.
1. Run migrations with `docker-compose -f local.yml exec django python manage.py migrate`.
1. Open Django shell with `docker-compose -f local.yml run django python manage.py shell_plus` and run (it takes about 1 minute):
```python
from sprints.dashboard.automation import *
from sprints.dashboard.libs.jira import *
conn = CustomJira(
server=settings.JIRA_SERVER, …
```
> Fix detecting sprint injections

- sprints/dashboard/automation.py
- sprints/dashboard/tests/test_automation.py
This fixes the edge case when Jira groups changelogs. It looks like there are multiple cases when updates to the tickets are grouped together - e.g. changing the sprint can be mixed with changing the ticket's estimate.
1. Set `.env` (you can find them [here](https://vault.opencraft.com:8200/ui/vault/secrets/secret/show/core/Sprints%20Development%20Envs)). There were some recent changes.
1. Build the backend with `docker-compose -f local.yml build --pull`.
1. Run migrations with `docker-compose -f local.yml exec django python manage.py migrate`.
1. Open Django shell with `docker-compose -f local.yml run django python manage.py shell_plus` and run (it takes about 1 minute):
```python
from sprints.dashboard.automation import *
from sprints.dashboard.libs.jira import *
conn = CustomJira( …
```
> [Hotfix] Fix grouped changelogs case in sprint injection detection

- sprints/dashboard/automation.py
- sprints/dashboard/tasks.py
- sprints/dashboard/tests/test_automation.py
This fixes a case of having a different list of participants and scrum masters - e.g. for the bot account, which should not be a participant of an estimation session.
It also adds task filtering for the estimation session.
> [Hotfix] Fix assigning users to poker sessions, add task filtering

- sprints/dashboard/libs/jira.py
- sprints/dashboard/tasks.py
This fixes the HTTP 500 response from Jira while updating the session for some cells. It's related to undefined handling of user names vs user keys by Jira.
> [Hotfix] Fix updating Jira poker sessions

- sprints/dashboard/tasks.py
It has been sending an email in every task run.
> [Hotfix] Do not send emails on the estimation session update

- config/settings/base.py
- sprints/dashboard/libs/jira.py
- sprints/dashboard/tasks.py
This is the third approach, as it does not use the native Jira API way of handling this.
> [BB-3174] Disable Jira session notifications v3

- sprints/dashboard/tasks.py
- sprints/dashboard/tests/test_utils.py
- sprints/dashboard/utils.py
**Description**
---
This PR changes the current FF-1, FF-2, DD-1, DD-2 role to Current Sprint FF,  Current Sprint DD, Future Sprint FF, and  Future Sprint DD so we can easily define the checklist of the responsibility of these rotational roles.
**Supporting information**
---
JIRA Ticket: [SE-4489](https://tasks.opencraft.com/browse/SE-4489)
**Testing instructions**
---
We have two projects to set up for the testing of this feature.
Sprints Project
-  Clone this repo locally
-  Change the value of these configurations as per staging env
```
JIRA_SERVER=
JIRA_USERNAME=  
JIRA_PASSWORD=
JIRA_CELL_ROLE_ACCOUNT=
JIRA_CELL_ROLES={"FF": [{"name": "Firefighter", "hours": 15, "story_points": 4}, {"name": "Community Relations", "hours": 1, "story_points": 0.5, "account": 33}], "DD": [{"name": …
```
> [SE-4489] Adding current and next sprint firefighter context to the checklist

- sprints/dashboard/tasks.py
- sprints/dashboard/tests/test_utils.py
- sprints/dashboard/utils.py
This unifies sprint start/end dates by using the higher-level API instead of the native Jira one. The also allows separating the Sprints logic from the Jira-specific features. It's the first step towards creating an abstraction, which is going to be used by [plugins](https://gitlab.com/opencraft/dev/sprints/-/blob/master/docs/discoveries/2.%20Sprints%20v2%20UX.md#12-plugins).
It also adds some tests.
Fixes https://gitlab.com/opencraft/dev/sprints/-/issues/16 (the content of this issue is a little different, so I've added a comment to explain the approach in `complete_sprint_task`).
This is going to be tricky to test manually, as it would require sprint manager permissions + manual API calls, as our Jira version has a very limited way of editing sprint details. Therefore, we can rely on …
> [BB-4548] Unify sprint start/end dates
